[package]
name = "concurrency-quiz"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

[dependencies]
crossbeam-deque = "0.7"
log = "0.4"
env_logger = "0.6"
parking_lot = "0.7"
